
library(shiny)
library(bslib)
library(ggplot2)
library(scales)
library(shinyjs)
library(shinylive)
library(httpuv)

# Define UI for application that draws a histogram
ui <- page_navbar(
  title = "Estimating MDMA Monopoly Revenues",
  theme = bs_theme(version = 5),
  useShinyjs(),
  
  nav_panel(
    "About",
    card(
      card_header("Background & Formula"),
      tags$p(
        tags$strong("This shiny app compliments the report: Counting the Returns MDMA quickscan, by the municipality of Amsterdam"),
        "The quickscan provides an estimate of the potential revenue that could be generated by a state-run MDMA monopoly in the Netherlands. As there is no precedent for a regulated MDMA market, our analysis is partly based on educated guesses. For instance, we have made assumptions regarding the production costs of MDMA and the proportion of consumers who would switch to a regulated market. This app enables you to easily calculate your own revenue estimates for a state-run MDMA monopoly, based on various assumptions. For more elaborate definitions, please consult the accompanying report.",
        tags$br(),
        tags$p(
          style = "margin-top: 1rem;",
          "Revenue is calculated using the following formula: ",
          tags$span(
            style = "white-space: nowrap;",
            tags$em("Number of consumers"), " × ",
            tags$em("Frequency"), " × ",
            tags$em("Intensity"), " × ",
            tags$em("Market capture"), " × (",
            tags$em("Price"), " − ", tags$em("Cost"), ")."
          )
        )
      )
    )
  ),
  
  # ---- PAGE 1: Assumptions ----
  nav_panel(
    "Analysis",
    layout_sidebar(
      
      sidebar = sidebar(
        title = "Estimates",
        open = TRUE,            # keep sidebar open by default
        width = 360,            # tweak to taste
        
        # subtitle under the title
        div(class = "small text-muted mb-3",
            "There is an open field and a slider for each variable below. Enter your best guess in the open fields to produce the number below. The sliders allow you to set a range and generate multiple simulated outcomes. These are shown in the figure on the right."
        ),
        # add space around subtitle
        tags$hr(class = "my-2"),
        
        accordion(
          id = "assumption_panels", 
          multiple = FALSE,      # only one panel open at a time
          open = c("Simulation settings"),  # default open panels
        
          # --- Number of consumers ---
          accordion_panel(
            "Number of consumers",
            p(class = "text-muted small", "Estimated number of annual MDMA consumers in the Netherlands."),
            numericInput("num_consumers", "Number of consumers", value = 550000, min = 0, step = 1000),
            sliderInput("num_consumers_range", "Range", min = 0, max = 18000000, value = c(300000, 800000), step = 1000)
          ),
          
          # --- Frequency ---
          accordion_panel(
            "Frequency",
            h6(class = "text-muted", "Annual sessions per consumer."),
            checkboxInput("use_empirical", "Use empirical data from Party Panel", value = TRUE),
            
            # Manual inputs (visible always; disabled when 'use_empirical' is TRUE)
            numericInput(
              "freq_point", "Point estimate (sessions/year)",
              value =  round(4.7, 1), min = 0, step = 0.5
            ),
            sliderInput(
              "freq_range", "Range (sessions/year)",
              min = 0, max = 100, value = c(1, 30), step = 1
            ),
            helpText("When empirical data is selected, the manual controls are shown but disabled.")
          ),
          
          # --- Intensity ---
          accordion_panel(
          "Intensity",
          p(class = "text-muted small", "Average number of pills per session."),
          numericInput("intensity_point", "Pills per session", value = 2, min = 0, step = 0.1),
          sliderInput("intensity_range",   "Range", min = 0, max = 10, value = c(1, 3), step = 0.01),
          ),
          
          #--- Market capture ---
          accordion_panel(
          "Market capture",
          p(class = "text-muted small", "Proportion of consumers who switch to the regulated market."),
          numericInput("mkr_point", "Point estimate", value = 0.8, min = 0, max = 1, step = 0.01),
          sliderInput("mkr_range", "Range", min = 0, max = 1, value = c(0.4, 0.9), step = 0.01),
          ),
          
          # --- Price & Cost ---
          accordion_panel(
          "Price & Cost (€/pill)",
          p(class = "text-muted small", "Cost is total marginal cost per pill."),
          numericInput("price_point", "Price point estimate", value = 5, min = 0, step = 0.1),
          sliderInput("price_range", "Price range", min = 0, max = 20, value = c(3, 8), step = 0.1),
          numericInput("cost_point", "Cost point estimate", value = 2, min = 0, step = 0.1),
          sliderInput("cost_range", "Cost range", min = 0, max = 20, value = c(1, 8), step = 0.1)
          ),
          
          #--- Simulation settings ---
          accordion_panel(
            "Simulation settings",
            h6(class = "text-muted", "Control Monte Carlo sampling."),
            numericInput(
              "sim_n", "Number of draws (n)",
              value = 10000, min = 100, max = 1e6, step = 1000
            ),
            numericInput(
              "sim_seed", "Random seed",
              value = 1234, min = 0, step = 1
            ),
            helpText("Larger n gives smoother plots but takes longer to compute.")
          )
        ),
      
      
      # ---- Main content (outputs) ----
      card(
        card_header("Expected revenue"),
        h1(textOutput("point_estimate", container = h2), class = "display-5")
      )
    ),
      
      # ---- Simulation results ----
      card(
        card_header("Variation in expected revenue"),
        plotOutput("revenue_plot", height = "420px")
      )
    )
  ),
  
  # ---- PAGE 2 (blank for now) under a menu ----
  nav_menu(
    "More",
    nav_panel(
      "Frequency (coming soon)",
      fluidPage(
        h4("Frequency"),
        p("This page will host frequency inputs, data loading, and related outputs.")
      )
    )
  )
)

server <- function(input, output, session) {
  
  # Enable/disable frequency inputs based on empirical checkbox
  observe({
    if (isTRUE(input$use_empirical)) {
      shinyjs::disable("freq_point")
      shinyjs::disable("freq_range")
    } else {
      shinyjs::enable("freq_point")
      shinyjs::enable("freq_range")
    }
  })
  
  # Import empirical frequency 
  party_panel <- read.csv("Party_Panel.csv", check.names = FALSE)
  
  # drop the last five rows (your comment says five, not one)
  if (nrow(party_panel) >= 5) {
    party_panel <- party_panel[seq_len(nrow(party_panel) - 5), ]
  }
  
  party_panel[] <- lapply(party_panel, function(x) as.numeric(x))
  
  frequency_mean <- with(party_panel, sum(Gebruik * Frequencies, na.rm = TRUE) / sum(Frequencies, na.rm = TRUE))
  
  # Point estimate uses point inputs only
  revenue_point <- reactive({
    mkr  <- input$mkr_point
    p    <- input$price_point
    cst  <- input$cost_point
    inten <- input$intensity_point
    number_consumers <- input$num_consumers
    
    # choose frequency source
    freq <- if (isTRUE(input$use_empirical)) frequency_mean else input$freq_point
    
    number_consumers * freq * inten * mkr * (p - cst)
  })
  
  output$point_estimate <- renderText({
    val <- revenue_point()
    paste0("€ ", format(round(val, 0), big.mark = ","))
  })
  
  # ---- Monte Carlo simulation (reactive) ----
  sim_draws <- reactive({
    
    n    <- input$sim_n
    seed <- input$sim_seed
    number_consumers <- input$num_consumers
    
    
    set.seed(seed)  # we can make this user-set later
    
    # Inputs 
    inten_lower <- input$intensity_range[1]
    inten_upper   <- input$intensity_range[2]
    
    mkr_lower  <- input$mkr_range[1]
    mkr_upper  <- input$mkr_range[2]
    
    price_lower <- max(0, input$price_range[1])
    price_upper <- max(price_lower, input$price_range[2])  
    
    cost_lower  <- max(0, input$cost_range[1])
    cost_upper  <- max(cost_lower, input$cost_range[2])
    
    # Draws (vectorized)
    intensity <- runif(n, min = inten_lower, max = inten_upper)
    market    <- runif(n, min = mkr_lower,   max = mkr_upper)
    price     <- runif(n, min = price_lower, max = price_upper)
    cost      <- runif(n, min = cost_lower,  max = cost_upper)
    
    if (isTRUE(input$use_empirical)) {
      # empirical sampling (first 21 rows)
      freq <- sample(
        x       = party_panel$Gebruik[1:21],
        size    = n, replace = TRUE,
        prob    = party_panel$Frequencies[1:21]
      )
    } else {
      # manual uniform range
      fmin <- max(0, input$freq_range[1])
      fmax <- max(fmin, input$freq_range[2])
      freq <- runif(n, min = fmin, max = fmax)
    }
    
    revenue <- number_consumers * freq * intensity * market * (price - cost)
    revenue
  })
  
  # # ---- Point estimate ----
  # revenue_estimate_freq <- reactive({
  #   number_consumers * frequency_mean *
  #     max(0, input$intensity_point) *
  #     max(0, min(1, input$mkr_point)) *
  #     (max(0, input$price_point) - max(0, input$cost_point))
  # })
  
  # ---- Histogram render ----
  output$revenue_plot <- renderPlot({
    library(ggplot2)
    library(scales)
    
    revenue <- sim_draws()
    rev_est <- revenue_point()
    
    # Quantiles + point estimate
    qs <- quantile(revenue, c(0.05, 0.5, 0.95), na.rm = TRUE)
    ref_lines <- data.frame(
      type  = c("5th percentile", "Median", "95th percentile", "Point estimate"),
      value = c(qs[1], qs[2], qs[3], rev_est)
    )
    
    # Build a base histogram first to learn the y scale
    bins <- 60
    p0 <- ggplot(data.frame(revenue = revenue), aes(x = revenue)) +
      geom_histogram(bins = bins, alpha = 0.85)
    
    gb <- ggplot_build(p0)
    ymax <- max(gb$data[[1]]$count, na.rm = TRUE)   # histogram's tallest bar
    seg_frac <- 0.1                                # how tall the markers should be (0–1)
    below_frac <- 0.04
    ref_lines$ymin <- -ymax * below_frac
    ref_lines$ymax <- ymax * seg_frac
    
    # Re-draw with capped vertical markers
    ggplot(data.frame(revenue = revenue), aes(x = revenue)) +
      geom_histogram(bins = bins, alpha = 0.85) +
      geom_linerange(
        data = ref_lines,
        aes(x = value, ymin = ymin, ymax = ymax, color = type),
        linewidth = 1
      ) +
      scale_color_manual(
        values = c(
          "Point estimate"   = "blue",
          "Median"           = "black",
          "5th percentile"   = "grey50",
          "95th percentile"  = "grey50"
        ),
        name = NULL
      ) +
      labs(
        title = "Projected Annual Revenue of a State MDMA Monopoly",
        x = "Revenue", y = "Count"
      ) +
      scale_x_continuous(labels = label_number(prefix = "€", big.mark = ",")) +
      theme_minimal(base_size = 13) +
      theme(
        plot.background = element_rect(fill = "white", color = NA),
        legend.position = "bottom"
      )
  })
  
  
  
  
}

# Run the application 
shinyApp(ui = ui, server = server)
